### ISSUE TITLE
Review docker file for root usage

### ISSUE THREAD

**Issue by tmckayus** [red-hat-data-services/odh-deployer#2]
The Dockerfile sets the HOME env var to /root, does this imply the image is running as root? Does it need to?  If it isn't running as root, HOME should be set somewhere else.

**Comment by tmckayus** [comment]
@crobby ptal, @vpavlin fyi

**Comment by crobby** [comment]
I just noticed this now.  It looks like it's not actually running as root and use of HOME /root is likely unnecessary.  Should be a simple fix.  Thanks.
